<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
    </PropertyGroup>
    
    <ItemGroup>
        <Resource Include="Images\WinterMap.jpg" />
        <Resource Include="Images\ForestMap.jpg" />
        <None Remove="Images\SettingsButton.png" />
        <Resource Include="Images\SettingsButton.png" />
        <None Remove="Images\StartButton.png" />
        <Resource Include="Images\StartButton.png" />
        <None Remove="Images\StartScreen.png" />
        <Resource Include="Images\StartScreen.png" />
        <None Remove="Images\ChFMap.jpg" />
        <Resource Include="Images\ChFMap.jpg" />
        <None Remove="Images\ChWMap.jpg" />
        <Resource Include="Images\ChWMap.jpg" />
        <None Update="Winter.json">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Forest.json">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Remove="Images\car1.png" />
        <Resource Include="Images\car1.png">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Resource>
        <None Remove="Images\car2.png" />
        <Resource Include="Images\car2.png" />
        <None Remove="Images\car3.png" />
        <Resource Include="Images\car3.png" />
        <None Remove="Images\car4.png" />
        <Resource Include="Images\car4.png" />
        <None Remove="Images\car5.png" />
        <Resource Include="Images\car5.png" />
        <None Remove="Images\car6.png" />
        <Resource Include="Images\car6.png" />
        <None Remove="Images\car7.png" />
        <Resource Include="Images\car7.png" />
        <None Remove="Images\CarButton.png" />
        <Resource Include="Images\CarButton.png" />
    </ItemGroup>
    
    <ItemGroup>
      <None Remove="Music\MenuSong.mp3" />
      <Content Include="Music\MenuSong.mp3">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <None Remove="Music\RaceSong.mp3" />
      <Content Include="Music\RaceSong.mp3">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
    </ItemGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\..\lab\lab.csproj" />
    </ItemGroup>
    
</Project>
